name: 'Change json parameter'
description: 'Change json parameter'
inputs:
  file:
    description: 'json file to change'
    required: true
  parameter:
    description: 'parameter to change'
    required: true
  value:
    description: 'value to set'
    required: true
  email: 
    description: 'email of the commit user'
    required: false
    default: user@domain.com
  name:
    description: 'name of the commit user'
    required: false
    default: CI
runs:
  using: "composite"
  steps:
    - name: Install jq
      uses: dcarbone/install-jq-action@v2.1.0

    - name: update version
      run: |
        cp ${{ inputs.file }} tmp.json
        jq '.${{ inputs.parameter }} = "${{ inputs.value }}"' tmp.json > ${{ inputs.file }}
        rm tmp.json
      shell: bash

    - name: commit new version file
      run: |
        git config --global user.email "${{ inputs.email }}"
        git config --global user.name "${{ inputs.name }}"
        git add ${{ inputs.file }}
        git commit -m "chore: versioning via CI [skip ci]"
        git push
      shell: bash